output_file: selected_code.txt
include:
  # - src/editor/*.zig
  - transitions.py
  - video_utils.py
  - whisper_parser.py
  - subtitle_effects.py
  - process_transcription.py
  - cut_transition.py
  - corrections.json
  # - merge_videos.py
  - lip_sync.py
  - script.json
  - 鹿茸血文案.txt